URL_IMAGE = "http://192.168.1.221:8000/media/"
URL_REPORTS = "http://192.168.1.221:8000/therapist/report?ther_id="

salt = "2m-6CN6C4QRe8=2Xep8G"

responseCode = "response_code"
responseText = "response_text"
responseList = "response_list"
sessionToken = "session_token"
detail = "detail"
_id = "id"
hari = "hari"
tanggal = "tanggal"
tempat = "tempat"
judul = "judul"
bulan = "bulan"
deskripsi = "deskripsi"
pemateri = "pemateri"
poster_path = "poster_path"
nama = "nama"
ig_akun = "ig_akun"
from_date = "from_date"
to_date = "to_date"
full_date = "full_date"